-- Erzeugt von erzeuge_import.py — nicht von Hand ändern.
-- Inventar der ATC technology GmbH aus dem Bewertungsgutachten vom 05.08.2025.
begin;

-- Anschrift einmal, die Räume darunter.
insert into locations (company_id, name, kind, address)
values ('00b09d31-0231-4075-a44e-79a497419e72', 'Betriebsstätte Röthenbach', 'site', 'Mühllach 11, 90552 Röthenbach an der Pegnitz');

insert into locations (company_id, parent_id, name, kind)
select '00b09d31-0231-4075-a44e-79a497419e72',
       (select id from locations where company_id = '00b09d31-0231-4075-a44e-79a497419e72' and kind = 'site'),
       r.name, 'room'
  from (values
           ('Halle Fertigung'),
           ('Lager'),
           ('Werkstattbüro'),
           ('Halle Montage'),
           ('Sägerei'),
           ('Kompressorraum'),
           ('Außenbereich/Zelt'),
           ('Außenbereich'),
           ('Lager EP-ARMS'),
           ('Büro EP-ARMS'),
           ('Serverraum'),
           ('Besprechungszimmer'),
           ('Konstruktionsbüro'),
           ('Büro Buchhaltung'),
           ('Fuhrpark')
       ) as r(name);

-- 103 Objekte in der Reihenfolge des Gutachtens, damit die
-- Inventarnummern der Positionsfolge entsprechen.
--
-- Der Wiederholtext der Bemerkung — Herkunft, Position, Anlagengruppe und
-- der Hinweis zum Fortführungswert — steht einmal unten im SELECT statt
-- hundertdreimal in den Daten. Das spart rund 30 kB und macht die Zeilen
-- lesbar: eine Zeile, ein Posten des Gutachtens.
with roh (pos, standort, kat, name, wortlaut, hersteller, modell, seriennr,
          status, zustand, wert, attr, gruppe, bemerkung, altnr) as (values
  (4, 'Halle Fertigung', 'furniture', '2 Metall-Schubladenschränke Lista', '2 Metall-Schubladenschränke, Fabr. Lista, 4 Auszüge, Inhalt: Werkzeuge, u.a. Wechselschneidplatten, Fräser, Spannhülsen',
   'Lista', null, null, 'in_stock', 'used', 100000, '{"afa_group": "MTA (15)", "set_size": 2}'::jsonb, 'MTA (15)', 'ggf. FE Luna Vermögensverwaltungsgesellschaft mbH, keine gesicherte Zuordnung möglich', null),
  (6, 'Halle Fertigung', 'machine', 'Auffangwanne', '1 Auffangwanne, ca. 2.000 x 800 mm, m. Gitterrostauflage',
   null, null, null, 'in_stock', 'used', 8000, '{}'::jsonb, 'MTA (15)', null, null),
  (7, 'Halle Fertigung', 'machine', 'mobiles Fasstransportgestell', '1 mobiles Fasstransportgestell',
   null, null, null, 'in_stock', 'used', 2000, '{}'::jsonb, 'MTA (15)', null, null),
  (8, 'Halle Fertigung', 'furniture', '4 mobile Werkbänke', '4 mobile Werkbänke, aus Aluprofilen, 2 Ebenen, 3 x m. Schubladenunterbau, Fabr. Garant',
   null, null, null, 'in_stock', 'used', 40000, '{"afa_group": "MTA (15)", "set_size": 4}'::jsonb, 'MTA (15)', null, null),
  (9, 'Halle Fertigung', 'machine', 'Hartgestein-Messtisch', '1 Hartgestein-Messtisch, 1.600 x 1.000 x 150 mm, Gewicht 768 kg, Untergestell, Hartgesteinplatte, m. Schraubhülsen versehen',
   null, null, null, 'in_stock', 'used', 40000, '{}'::jsonb, 'MTA (15)', null, null),
  (10, 'Halle Fertigung', 'machine', 'Druckluftkessel OKS', '1 Druckluftkessel, Fabr. OKS, Bj 2016, SN 8833, Fassungsvermögen 250 l, stehend',
   'OKS', null, '8833', 'in_stock', 'used', 20000, '{"year_built": 2016}'::jsonb, 'MTA (15)', null, null),
  (11, 'Halle Fertigung', 'machine', 'Elektrokabel-Aufroller Elektron', '1 Elektrokabel-Aufroller, Fabr. Elektron',
   'Elektron', null, null, 'in_stock', 'used', 3000, '{}'::jsonb, 'MTA (15)', null, null),
  (12, 'Halle Fertigung', 'furniture', 'Blechschrank CP', '1 Blechschrank, Fabr. CP, 2-türig, 1.500 x 600 mm',
   'CP', null, null, 'in_stock', 'used', 3000, '{"afa_group": "BGA (16)", "dimensions": "1.500 x 600 mm"}'::jsonb, 'BGA (16)', null, null),
  (13, 'Halle Fertigung', 'machine', 'tragbare Umreifungsbandhaspel', '1 tragbare Umreifungsbandhaspel, 2 manuelle Spann-/Verschlusszangen',
   null, null, null, 'in_stock', 'used', 8000, '{}'::jsonb, 'BGA (16)', null, null),
  (14, 'Halle Fertigung', 'furniture', '2 Montageregale', '2 Montageregale, L 1.000 mm, Schraub-/Stecksystem, 1 x m. Schrägböden, 4/5 Ebenen',
   null, null, null, 'in_stock', 'used', 5000, '{"afa_group": "BGA (16)", "set_size": 2}'::jsonb, 'BGA (16)', null, null),
  (15, 'Halle Fertigung', 'machine', '2 mobile Spänekippmulden Bauer SKK800', '2 mobile Spänekippmulden, Fabr. Bauer, Typ SKK800, Bj 2014/2016, Fassungsvermögen 800 l, Tragfähigkeit 300 kg',
   'Bauer', 'SKK800', null, 'in_stock', 'used', 40000, '{"year_built": 2014}'::jsonb, 'BGA (16)', null, null),
  (16, 'Halle Fertigung', 'machine', '3 mobile Spänekippmulden', '3 mobile Spänekippmulden, Fassungsvermögen 800 l',
   null, null, null, 'in_stock', 'used', 60000, '{}'::jsonb, 'BGA (16)', null, null),
  (17, 'Halle Fertigung', 'machine', 'Deichselhubwagen Ameise', '1 Deichselhubwagen, Fabr. Ameise, Tragfähigkeit 2.000 kg',
   'Ameise', null, null, 'in_stock', 'used', 8000, '{}'::jsonb, 'BGA (16)', null, null),
  (18, 'Halle Fertigung', 'machine', '2 Etagenwagen Fetra', '2 Etagenwagen, Fabr. Fetra, 2 Ebenen',
   'Fetra', null, null, 'in_stock', 'used', 8000, '{}'::jsonb, 'BGA (16)', null, null),
  (19, 'Halle Fertigung', 'machine', 'Akku-Bohrschrauber Bosch GSR 18V-28', '1 Akku-Bohrschrauber, Fabr. Bosch, Typ GSR 18V-28, Ladegerät, Ersatzakku, 2 Kabeltrommeln, 1 x Kunststoff, 2 LED-Strahler',
   'Bosch', 'GSR 18V-28', null, 'in_stock', 'used', 4000, '{}'::jsonb, 'BGA (16)', null, null),
  (20, 'Halle Fertigung', 'machine', 'Tischbohrmaschine HG 8', '1 Tischbohrmaschine, Fabr. HG, Typ 8, kleiner Schraubstock',
   'HG', '8', null, 'in_stock', 'used', 8000, '{}'::jsonb, 'BGA (16)', null, null),
  (21, 'Halle Fertigung', 'furniture', 'Metallwerkbank', '1 Metallwerkbank, L 2.000 mm, m. Zwischenboden, Holz, Schublade, Gitterrückwand, 1 Posten Handwerkzeuge, geringer Umfang',
   null, null, null, 'in_stock', 'used', 8000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', null, null),
  (22, 'Halle Fertigung', 'machine', 'Druckluftkessel OKS', '1 Druckluftkessel, Fabr. OKS, Bj 2015, SN 8556, Fassungsvermögen 250 l',
   'OKS', null, '8556', 'in_stock', 'used', 20000, '{"year_built": 2015}'::jsonb, 'BGA (16)', null, null),
  (23, 'Halle Fertigung', 'machine', 'mobiler Industriesauger Ruwac SPS250-W24', '1 mobiler Industriesauger, Fabr. Ruwac, Typ SPS250-W24, 3,21 kW, SN SPS250/20171045',
   'Ruwac', 'SPS250-W24', 'SPS250/20171045', 'in_stock', 'used', 70000, '{"power_kw": 3.21}'::jsonb, 'BGA (16)', null, null),
  (25, 'Halle Fertigung', 'machine', 'Werkzeugschrumpfgerät Kelch i-tec L', '1 Werkzeugschrumpfgerät, Fabr. Kelch, Typ i-tec L, Bj 2013',
   'Kelch', 'i-tec L', null, 'in_stock', 'used', 95000, '{"year_built": 2013}'::jsonb, 'MTA (15)', null, '40006'),
  (26, 'Halle Fertigung', 'machine', 'Werkzeug-Voreinstellgerät Promat Kenova Set Line V224', '1 Werkzeug-Voreinstellgerät, Fabr. Promat, Typ Kenova Set Line V224, Bj 2013',
   'Promat', 'Kenova Set Line V224', null, 'in_stock', 'used', 70000, '{"year_built": 2013}'::jsonb, 'MTA (15)', null, '22012'),
  (27, 'Halle Fertigung', 'furniture', 'Werkbank Garant', '1 Werkbank, Fabr. Garant, 2 Unterschränke, 6 Auszüge bzw. 4 Auszüge/Tür, Auflageplatte m. Metallabdeckung, Schraubstock, Steilkegel-Einspannvorrichtung, Fabr. Knuth, Schubladeninhalt: Handwerkzeuge, Spannmittel, geringer Umfang',
   'Garant', null, null, 'in_stock', 'used', 40000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', null, null),
  (28, 'Halle Fertigung', 'machine', 'tragbares Batterieladegerät Ultimate Speed ULG12B3', '1 tragbares Batterieladegerät, Fabr. Ultimate Speed, Typ ULG12B3',
   'Ultimate Speed', 'ULG12B3', null, 'in_stock', 'used', 5000, '{}'::jsonb, 'BGA (16)', null, null),
  (29, 'Halle Fertigung', 'furniture', '2 Blechschränke', '2 Blechschränke, 2.000 x 1.000 mm, 2-türig, Inhalt: Maschinenwerkzeuge, Fräser, in Lagersichtkästen, geringer Umfang, 1 Posten Werkzeugaufnahmen, SK40, ca. 50 Stck., 1 Posten Bohrer u. Fräser',
   null, null, null, 'in_stock', 'used', 34000, '{"afa_group": "BGA (16)", "set_size": 2, "dimensions": "2.000 x 1.000 mm"}'::jsonb, 'BGA (16)', 'ggf. FE Luna Vermögensverwaltungsgesellschaft mbH, keine gesicherte Zuordnung möglich', null),
  (30, 'Halle Fertigung', 'machine', 'Flaschenzug Chain Block HS', '1 Flaschenzug, Fabr. Chain Block, Typ HS, Tragfähigkeit 1 t, 1 Posten Luft- und Wasserschläuche, Überbrückungskabel, 1 Posten Rundschlingen u. Spanngurte, lagernd in Blechkiste',
   'Chain Block', 'HS', null, 'in_stock', 'used', 8000, '{}'::jsonb, 'BGA (16)', null, null),
  (31, 'Halle Fertigung', 'machine', 'tragbarer Hochdruckreiniger Kränzle Power Jet', '1 tragbarer Hochdruckreiniger, Fabr. Kränzle, Typ Power Jet, 115 bar, m. Sprühlanze',
   'Kränzle', 'Power Jet', null, 'in_stock', 'used', 14000, '{}'::jsonb, 'BGA (16)', null, null),
  (32, 'Halle Fertigung', 'machine', 'Pneumatik-Fasspumpe', '1 Pneumatik-Fasspumpe',
   null, null, null, 'in_stock', 'used', 3000, '{}'::jsonb, 'BGA (16)', null, null),
  (34, 'Halle Fertigung', 'machine', 'Alu-Anstellleiter Krause', '1 Alu-Anstellleiter, Fabr. Krause, 12-stufig',
   'Krause', null, null, 'in_stock', 'used', 3000, '{}'::jsonb, 'BGA (16)', null, null),
  (35, 'Lager', 'machine', 'Pneumatik-Kniehebelpresse Gechter 8KN HKPL', '1 Pneumatik-Kniehebelpresse, Fabr. Gechter, Typ 8KN HKPL, Bj 2015',
   'Gechter', '8KN HKPL', null, 'in_stock', 'used', 68000, '{"year_built": 2015}'::jsonb, 'MTA (15)', null, null),
  (36, 'Lager', 'machine', 'Druckluft-Kartuschenpresse', '1 Druckluft-Kartuschenpresse, 2 Aufnahmen',
   null, null, null, 'in_stock', 'used', 8000, '{}'::jsonb, 'BGA (16)', null, null),
  (37, 'Lager', 'machine', '2 Hochdruckspannstöcke Garant 36 0510 12', '2 Hochdruckspannstöcke, Fabr. Garant, Typ 36 0510 12',
   'Garant', '36 0510 12', null, 'in_stock', 'used', 140000, '{}'::jsonb, 'BGA (16)', null, null),
  (38, 'Lager', 'furniture', '6 Leichtbauregale', '6 Leichtbauregale, verzinkt/blau, L 1.000 mm, 5 Ebenen, Blechschrank, 2-türig, Tresor, antik, 2-türig',
   null, null, null, 'in_stock', 'used', 10000, '{"afa_group": "BGA (16)", "set_size": 6}'::jsonb, 'BGA (16)', null, null),
  (39, 'Lager', 'machine', 'Posten Altbauteile', '1 Posten Altbauteile, u.a. Pneumatik, 1 Posten Schaltschränke, Elektro-/Datenkabel',
   null, null, null, 'in_stock', 'used', 50000, '{}'::jsonb, 'BGA (16)', null, null),
  (41, 'Werkstattbüro', 'it', 'PC Lenovo Thinkstation D20', '1 PC, Fabr. Lenovo, Typ Thinkstation D20, Xeon, PC, Fabr. HP, Typ Z620 Workstation, Xeon, PC, Noname, außer Betrieb, 4 27"-Monitore, Fabr. BenQ/Asus, 2 Tastaturen, 2 PC-Lautsprecher',
   'Lenovo', 'Thinkstation D20', null, 'in_stock', 'defect', 20000, '{}'::jsonb, 'BGA (16)', null, null),
  (42, 'Werkstattbüro', 'it', 'Laserdrucker HP LaserJet CP1525N Color', '1 Laserdrucker, Fabr. HP, Typ LaserJet CP1525N Color',
   'HP', 'LaserJet CP1525N Color', null, 'in_stock', 'used', 2000, '{}'::jsonb, 'BGA (16)', null, null),
  (47, 'Halle Montage', 'machine', 'Etagenwagen Fetra', '1 Etagenwagen, Fabr. Fetra, 2 Ebenen',
   'Fetra', null, null, 'in_stock', 'used', 3000, '{}'::jsonb, 'BGA (16)', null, null),
  (52, 'Halle Montage', 'machine', 'Bohrhammer Hilti EE17', '1 Bohrhammer, Fabr. Hilti, Typ EE17, Zubehör, im Koffer',
   'Hilti', 'EE17', null, 'in_stock', 'used', 14000, '{}'::jsonb, 'BGA (16)', null, null),
  (53, 'Halle Montage', 'furniture', 'Metall-Schubladenschrank Hahn & Kolb', '1 Metall-Schubladenschrank, Fabr. Hahn & Kolb, L 2.000 mm, 8 Auszüge',
   'Hahn & Kolb', null, null, 'in_stock', 'used', 8000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', 'Bewertung ohne Inhalt, da Umlaufvermögen', null),
  (54, 'Halle Montage', 'furniture', 'Blechschrank', '1 Blechschrank, 2-türig, 1.600 x 600 mm, Inhalt: Lagersichtkästen, Schaltschrank, Fabr. Siemens, umgebaut zum Lagerschrank, Inhalt: div. Kunststoff-Sortimentskästen, u.a. Böllhoff, ohne Inhalt oder unvollständig, div. Werkzeuge',
   null, null, null, 'in_stock', 'used', 5000, '{"afa_group": "BGA (16)", "dimensions": "1.600 x 600 mm"}'::jsonb, 'BGA (16)', 'Bewertung ohne Verbrauchsmaterial, da Umlaufvermögen', null),
  (55, 'Halle Montage', 'furniture', 'Werkstattwagen', '1 Werkstattwagen, Inhalt: Handwerkzeuge, geringer Umfang',
   null, null, null, 'in_stock', 'used', 12000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', null, null),
  (60, 'Halle Montage', 'machine', 'Magnetbohrmaschine Duss D32 II', '1 Magnetbohrmaschine, Fabr. Duss, Typ D32 II, Magnetständer WS',
   'Duss', 'D32 II', null, 'in_stock', 'used', 15000, '{}'::jsonb, 'MTA (15)', null, null),
  (61, 'Halle Montage', 'furniture', 'Metallschubladenschrank Kardex', '1 Metallschubladenschrank, Fabr. Kardex, Inhalt: Maschinenwerkzeuge, geringer Umfang, Blechkiste, Inhalt: Gewindeschneideisen',
   'Kardex', null, null, 'in_stock', 'used', 10000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', null, null),
  (62, 'Halle Montage', 'furniture', 'Schaltschrank Siemens', '1 Schaltschrank, Fabr. Siemens, umgebaut zum Lagerschrank, Inhalt: 1 Posten Werkzeugaufnahmen, SK40, ca. 25 Stck., 1 Posten Werkzeuge, Fräser, Reibahle, Entmagnetisierplatte, Metallschrank, Fabr. Lampertz, Inhalt: Teilapparat, Spannmittel, Maschinenzubehör',
   'Siemens', null, null, 'in_stock', 'used', 30000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', null, null),
  (66, 'Halle Montage', 'machine', 'Entgratmaschine Günter Holl KS200', '1 Entgratmaschine, Fabr. Günter Holl, Typ KS200, Bj 1968',
   'Günter Holl', 'KS200', null, 'in_stock', 'used', 5000, '{"year_built": 1968}'::jsonb, 'MTA (15)', null, null),
  (67, 'Halle Montage', 'machine', 'Flachstahl-Handbiegevorrichtung', '1 Flachstahl-Handbiegevorrichtung',
   null, null, null, 'in_stock', 'used', 5000, '{}'::jsonb, 'BGA (16)', null, null),
  (68, 'Halle Montage', 'machine', 'Bodenkehrmaschine Kärcher S650', '1 Bodenkehrmaschine, Fabr. Kärcher, Typ S650',
   'Kärcher', 'S650', null, 'in_stock', 'used', 4000, '{}'::jsonb, 'BGA (16)', null, null),
  (69, 'Halle Montage', 'machine', 'Posten Handmaschinen', '1 Posten Handmaschinen, best. aus: Handkreissäge, Fabr. Flex, Typ CSM4060, Zubehör, im Koffer, Bohrhammer, Fabr. Impex, Typ DS70, m. Zubehör, im Koffer, Winkelschleifer, Fabr. Bosch, Typ GWS1100, Winkelschleifer, Fabr. Flex, Typ L1109FE, Winkelschleifer, Fabr. Kingcraft, Typ KAG125/950, Zweihand-Bohrmaschine, Fabr. Einhell, Typ BFMR1100, Winkelschleifer, Fabr. Hikoki, Bohrmaschine, Fabr. Fein, Winkelschleifer, Fabr. Kingcraft, Akku-Bohrschrauber, Fabr. Hilti, Typ SF2-A, Zubehör, im Koffer, Säbelsäge, Fabr. Dewalt, Typ DW304PK, Zubehör, im Koffer, Akku-Bohrschrauber, Fabr. Bosch, Akku-Handleuchte, Ersatzakku, Ladegerät, Koffer, Schlagbohrmaschine, Fabr. Metabo, Typ SBE900 Impuls, m. Koffer, 1 Posten Autogenschweißspitzen, im Blechkoffer, 4 Maschinenkoffer, ohne Inhalt',
   null, null, null, 'in_stock', 'used', 50000, '{}'::jsonb, 'BGA (16)', null, null),
  (70, 'Halle Montage', 'furniture', 'Blechschrank', '1 Blechschrank, 2-türig, Inhalt: Bohrer, Maschinenwerkzeuge',
   null, null, null, 'in_stock', 'used', 14000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', 'ggf. FE Luna Vermögensverwaltungsgesellschaft mbH, keine gesicherte Zuordnung möglich', null),
  (71, 'Halle Montage', 'machine', 'Gewindeschneidkluppe Rems EVA', '1 Gewindeschneidkluppe, Fabr. Rems, Typ EVA, 5 Einsätze, m. Blechkiste',
   'Rems', 'EVA', null, 'in_stock', 'used', 10000, '{}'::jsonb, 'BGA (16)', null, null),
  (72, 'Halle Montage', 'machine', 'Akku-Spritzgerät Graco X-Force HD', '1 Akku-Spritzgerät, Fabr. Graco, Typ X-Force HD, m. Zubehör, Ersatzakku, Ladegerät, im Koffer',
   'Graco', 'X-Force HD', null, 'in_stock', 'used', 50000, '{}'::jsonb, 'MTA (15)', null, '40027'),
  (73, 'Halle Montage', 'machine', 'Gewindeschneidmaschine HG 23N', '1 Gewindeschneidmaschine, Fabr. HG, Typ 23N',
   'HG', '23N', null, 'in_stock', 'used', 3000, '{}'::jsonb, 'BGA (16)', null, null),
  (74, 'Halle Montage', 'machine', 'Bürstenentgratmaschine Berg & Schmid BUE200', '1 Bürstenentgratmaschine, Fabr. Berg & Schmid, Typ BUE200, Bj 2017',
   'Berg & Schmid', 'BUE200', null, 'in_stock', 'used', 42000, '{"year_built": 2017}'::jsonb, 'MTA (15)', null, null),
  (75, 'Halle Montage', 'machine', 'Tischbohrmaschine Rascher/Wörner TIBO13', '1 Tischbohrmaschine, Fabr. Rascher/Wörner, Typ TIBO13, SN 14210, Schraubstock',
   'Rascher/Wörner', 'TIBO13', '14210', 'in_stock', 'used', 8000, '{}'::jsonb, 'MTA (15)', null, null),
  (76, 'Halle Montage', 'machine', 'Tischbohrmaschine', '1 Tischbohrmaschine, höhenverstellbarer Bohrtisch',
   null, null, null, 'in_stock', 'used', 20000, '{}'::jsonb, 'MTA (15)', null, null),
  (77, 'Halle Montage', 'furniture', '2 Arbeitstische', '2 Arbeitstische, Metall/Holz, m. Zwischenboden',
   null, null, null, 'in_stock', 'used', 5000, '{"afa_group": "BGA (16)", "set_size": 2}'::jsonb, 'BGA (16)', null, null),
  (79, 'Halle Montage', 'furniture', 'Metall-Schubladenschrank', '1 Metall-Schubladenschrank, 7 Auszüge, Inhalt: Messmittel, Fräser, Wendeschneidplatten, Schneideisen, Spannmittel, Maschinenzubehör, u.a. Backenfutter',
   null, null, null, 'in_stock', 'used', 75000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', null, null),
  (81, 'Halle Montage', 'machine', '3 Etagenwagen Fetra', '3 Etagenwagen, Fabr. Fetra, 2 Ebenen',
   'Fetra', null, null, 'in_stock', 'used', 10000, '{}'::jsonb, 'BGA (16)', null, null),
  (82, 'Halle Montage', 'machine', '2 Etagenwagen', '2 Etagenwagen, älter, 1 x m. Spanplattenauflage',
   null, null, null, 'in_stock', 'used', 4000, '{}'::jsonb, 'BGA (16)', null, null),
  (87, 'Halle Montage', 'machine', 'tragbarer Schweißinverter Kjellberg GIF180', '1 tragbarer Schweißinverter, Fabr. Kjellberg, Typ GIF180',
   'Kjellberg', 'GIF180', null, 'in_stock', 'used', 55000, '{}'::jsonb, 'MTA (15)', null, null),
  (89, 'Halle Montage', 'machine', 'mobile Schweißrauchabsaugung S.Tec M802', '1 mobile Schweißrauchabsaugung, Fabr. S.Tec, Typ M802, Bj 2013, Volumenstrom 1.600 m³/h, Motorleistung 1,1 kW, SN 6907210171529, Betriebsstd. 153, flexibler Absaugschlauch',
   'S.Tec', 'M802', '6907210171529', 'in_stock', 'used', 50000, '{"year_built": 2013, "power_kw": 1.1, "operating_hours": 153}'::jsonb, 'MTA (15)', null, null),
  (90, 'Sägerei', 'machine', 'Alu-Bockleiter Krause', '1 Alu-Bockleiter, Fabr. Krause, 10-stufig',
   'Krause', null, null, 'in_stock', 'used', 8000, '{}'::jsonb, 'BGA (16)', null, null),
  (91, 'Sägerei', 'furniture', 'Metallregal Schäfer', '1 Metallregal, Fabr. Schäfer, 2.200 x 1.000 x 800 mm, 6 Ebenen',
   'Schäfer', null, null, 'in_stock', 'used', 6000, '{"afa_group": "BGA (16)", "dimensions": "2.200 x 1.000 x 800 mm"}'::jsonb, 'BGA (16)', null, null),
  (92, 'Sägerei', 'machine', '2 Staubsauger Kärcher WD5.600MP', '2 Staubsauger, Fabr. Kärcher, Typ WD5.600MP, stark verschmutzt',
   'Kärcher', 'WD5.600MP', null, 'in_stock', 'used', 6000, '{}'::jsonb, 'BGA (16)', null, null),
  (93, 'Sägerei', 'machine', 'Industriesauger Nilfisk Alto Attix 751-21', '1 Industriesauger, Fabr. Nilfisk Alto, Typ Attix 751-21',
   'Nilfisk Alto', 'Attix 751-21', null, 'in_stock', 'used', 12000, '{}'::jsonb, 'BGA (16)', null, null),
  (95, 'Sägerei', 'furniture', 'Kragarmregal', '1 Kragarmregal, best. aus: 3 Ständer, wandmontiert, verschweißt, 3 Ebenen',
   null, null, null, 'in_stock', 'used', 12000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', null, null),
  (97, 'Sägerei', 'machine', 'Staubsauger Nilfisk Body II 18', '1 Staubsauger, Fabr. Nilfisk, Typ Body II 18',
   'Nilfisk', 'Body II 18', null, 'in_stock', 'used', 3000, '{}'::jsonb, 'BGA (16)', null, null),
  (98, 'Sägerei', 'machine', 'tragbarer Stromverteiler Rev', '1 tragbarer Stromverteiler, Fabr. Rev, 2 x Kraftstrom, 4 x Lichtstrom',
   'Rev', null, null, 'in_stock', 'used', 3000, '{}'::jsonb, 'BGA (16)', null, null),
  (99, 'Sägerei', 'machine', '2 Hochdruck-Spannstöcke Homge HPAC-1600S CNC Multipower', '2 Hochdruck-Spannstöcke, Fabr. Homge, Typ HPAC-1600S CNC Multipower',
   'Homge', 'HPAC-1600S CNC Multipower', null, 'in_stock', 'used', 200000, '{}'::jsonb, 'BGA (16)', null, '22011'),
  (101, 'Sägerei', 'furniture', 'kleiner Metallschrank', '1 kleiner Metallschrank, 1.600 x 600 mm, 2-türig, Inhalt: Lagersichtkästen, Metallspind, 2-türig, Metall-Werkbank, Unterschrank, 4 Auszüge, Holz, defekt',
   null, null, null, 'in_stock', 'used', 7000, '{"afa_group": "BGA (16)", "dimensions": "1.600 x 600 mm"}'::jsonb, 'BGA (16)', null, null),
  (102, 'Sägerei', 'machine', 'Dreiwalzen-Rohr- und Profilbiegemaschine Klaus Zopf CM2000 BPR', '1 Dreiwalzen-Rohr- und Profilbiegemaschine, Fabr. Klaus Zopf, Typ CM2000 BPR, mobiler Untertisch',
   'Klaus Zopf', 'CM2000 BPR', null, 'in_stock', 'used', 35000, '{}'::jsonb, 'MTA (15)', null, null),
  (107, 'Sägerei', 'furniture', '2 Stehhilfen', '2 Stehhilfen',
   null, null, null, 'in_stock', 'used', 2000, '{"afa_group": "BGA (16)", "set_size": 2}'::jsonb, 'BGA (16)', null, null),
  (108, 'Kompressorraum', 'machine', 'Schraubenkompressor Kaeser Sigma-Profil SM11', '1 Schraubenkompressor, Fabr. Kaeser, Typ Sigma-Profil SM11, Bj 1993, SN 0119052, Leistung 7,5 kW, Volumenstrom 0,92 m³/min, Betriebsstd. 24.808, Druckluft-Kältetrockner, Fabr. Kaeser, Typ TA11, Druckluftbehälter, Fabr. Siap, Fassungsvermögen 400 l, Öl-Wasser-Trenner, Fabr. Kaeser, Typ Aquamat 2, Druckluftverrohrung, div. Filter',
   'Kaeser', 'Sigma-Profil SM11', '0119052', 'in_stock', 'used', 100000, '{"year_built": 1993, "power_kw": 7.5, "operating_hours": 24808}'::jsonb, 'MTA (15)', null, null),
  (110, 'Außenbereich/Zelt', 'machine', 'Treibgas-Gabelstapler Linde H30T', '1 Treibgas-Gabelstapler, Fabr. Linde, Typ H30T, Bj 2005, SN H2X393S00313, Tragfähigkeit 3.000 kg, hydr. Seitenschieber, Duplexmast, Betriebsstd. 5.956, Zubehör: 1 Paar Zinkenverlängerungen',
   'Linde', 'H30T', 'H2X393S00313', 'in_stock', 'used', 600000, '{"year_built": 2005, "operating_hours": 5956}'::jsonb, 'MTA (15)', null, '38004'),
  (111, 'Außenbereich/Zelt', 'machine', 'Elektro-Deichselhochhubwagen Pramac Lifter GX10/16', '1 Elektro-Deichselhochhubwagen, Fabr. Pramac Lifter, Typ GX10/16, Bj 2014, SN HL10080665, defekt, außer Betrieb gelagert, Tragfähigkeit 1.000 kg',
   'Pramac Lifter', 'GX10/16', 'HL10080665', 'retired', 'defect', 0, '{"year_built": 2014}'::jsonb, 'MTA (15)', null, null),
  (114, 'Außenbereich/Zelt', 'machine', 'mobil Auffangwanne Bauer', '1 mobil Auffangwanne, Fabr. Bauer, Fassungsvermögen 200 l',
   'Bauer', null, null, 'in_stock', 'used', 14000, '{}'::jsonb, 'BGA (16)', null, null),
  (115, 'Außenbereich/Zelt', 'machine', 'Plattentransportwagen', '1 Plattentransportwagen, verstellbare Bügelgriffe',
   null, null, null, 'in_stock', 'used', 5000, '{}'::jsonb, 'BGA (16)', null, null),
  (117, 'Außenbereich/Zelt', 'furniture', 'Posten Metallregale Schäfer', '1 Posten Metallregale, Fabr. Schäfer, Böden teilw. verbogen, L 4.000 mm',
   'Schäfer', null, null, 'in_stock', 'used', 8000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', null, null),
  (120, 'Außenbereich', 'furniture', 'Kragarmregal Schulte KR-ES', '1 Kragarmregal, Fabr. Schulte, Typ KR-ES, Bj 2021, demontiert, best. aus: 3 Ständer, einseitig, 5 Ebenen, Kragarmlänge 500 mm, Ständerhöhe 2.300 mm',
   'Schulte', 'KR-ES', null, 'in_stock', 'used', 42000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', null, '40033'),
  (121, 'Außenbereich', 'machine', 'Posten Altmaschinenteile', '1 Posten Altmaschinenteile, lagernd auf Lafette (Schrott)',
   null, null, null, 'in_stock', 'defect', 60000, '{}'::jsonb, 'BGA (16)', null, null),
  (122, 'Außenbereich', 'furniture', 'Gasflaschenschrank Asecos', '1 Gasflaschenschrank, Fabr. Asecos, verzinkt, 1-türig, H 1.400 mm, B 700 mm, T 500 mm',
   'Asecos', null, null, 'in_stock', 'used', 20000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', null, null),
  (127, 'Lager EP-ARMS', 'furniture', 'Lagerbühne', '1 Lagerbühne, SN 215041, Durchgangshöhe 2.000 mm, Belastung max. zul. 500 kg/m², 7.000 x 9.000 mm, Anbaumodul, 3.000 x 4.500 mm, Säulen-/Trageelemente verschraubt, Spanplattenauflage, im unteren Bereich m. Beleuchtung, seitl. m. Treppenaufgang, Rückbaukosten',
   null, null, '215041', 'in_stock', 'used', 750000, '{"afa_group": "BGA (16)", "dimensions": "7.000 x 9.000 mm"}'::jsonb, 'BGA (16)', 'immobilienangepasst', '40032'),
  (129, 'Lager EP-ARMS', 'machine', 'Gabelhubwagen', '1 Gabelhubwagen, grün, Tragfähigkeit 2.000 mm',
   null, null, null, 'in_stock', 'used', 8000, '{}'::jsonb, 'BGA (16)', null, null),
  (130, 'Lager EP-ARMS', 'machine', 'Druckluftbehälter', '1 Druckluftbehälter, vermutl. OKS, Fassungsvermögen 250 l',
   null, null, null, 'in_stock', 'used', 20000, '{}'::jsonb, 'BGA (16)', null, null),
  (131, 'Lager EP-ARMS', 'machine', 'manuelle hydraulische Werkstattpresse BGS', '1 manuelle hydraulische Werkstattpresse, Fabr. BGS, Kapazität 20 t, Bj. 2024, Hub 150 mm, B 530 mm, Arbeitsbereich 0 - 1.030 mm',
   'BGS', null, null, 'in_stock', 'used', 20000, '{"year_built": 2024}'::jsonb, 'MTA (15)', null, null),
  (137, 'Büro EP-ARMS', 'it', 'Notebook Lenovo V320', '1 Notebook, Fabr. Lenovo, Typ V320, Intel Core i5',
   'Lenovo', 'V320', null, 'in_stock', 'used', 15000, '{}'::jsonb, 'BGA (16)', null, null),
  (142, 'Serverraum', 'it', 'Server Synology RS818 Plus', '1 Server, Fabr. Synology, Typ RS818 Plus, 4 Festplatteneinschübe',
   'Synology', 'RS818 Plus', null, 'in_stock', 'used', 8000, '{}'::jsonb, 'BGA (16)', null, null),
  (143, 'Serverraum', 'it', 'Firewall Sophos SG-125', '1 Firewall, Fabr. Sophos, Typ SG-125, lt. Aussage End Of Life',
   'Sophos', 'SG-125', null, 'in_stock', 'defect', 5000, '{}'::jsonb, 'BGA (16)', null, null),
  (144, 'Serverraum', 'it', 'Server HP Proviant DL 380P', '1 Server, Fabr. HP, Typ Proviant DL 380P, Gen 8, 4 Festplatten',
   'HP', 'Proviant DL 380P', null, 'in_stock', 'used', 15000, '{}'::jsonb, 'BGA (16)', null, null),
  (145, 'Serverraum', 'it', 'Server HP Proviant DL 360E', '1 Server, Fabr. HP, Typ Proviant DL 360E, Gen 8, 4 Festplatten, Prozessor Intel Xeon, vermutl. außer Betrieb',
   'HP', 'Proviant DL 360E', null, 'in_stock', 'defect', 5000, '{}'::jsonb, 'BGA (16)', null, null),
  (146, 'Serverraum', 'it', 'USV APC Smart UPS 1500', '1 USV, Fabr. APC, Typ Smart UPS 1500',
   'APC', 'Smart UPS 1500', null, 'in_stock', 'used', 8000, '{}'::jsonb, 'BGA (16)', null, null),
  (147, 'Serverraum', 'it', 'Posten IT-Hardware', '1 Posten IT-Hardware, best. aus: 5 Rechner/Server, Switch, 2 Monitore, UPS, End Of Life',
   null, null, null, 'retired', 'defect', 0, '{}'::jsonb, 'BGA (16)', 'Entsorgung', null),
  (148, 'Serverraum', 'it', 'W-LAN-Modem AVM FRITZ!Box', '1 W-LAN-Modem, Fabr. AVM, Typ FRITZ!Box',
   'AVM', 'FRITZ!Box', null, 'in_stock', 'used', 4000, '{}'::jsonb, 'BGA (16)', null, null),
  (150, 'Besprechungszimmer', 'furniture', 'Flipchart', '1 Flipchart, mobil',
   null, null, null, 'in_stock', 'used', 2000, '{"afa_group": "BGA (16)"}'::jsonb, 'BGA (16)', null, null),
  (151, 'Konstruktionsbüro', 'machine', '3D-Messarm HEXAGON Absolute Arm RA-7312-4', '1 3D-Messarm, Fabr. HEXAGON, Typ Absolute Arm RA-7312-4, Bj 2018, SN 7312-5548-FA, Hartgesteinmessplatte, Fabr. Hommel, Typ Dura, Metall-Untergestell, Transportkoffer',
   'HEXAGON', 'Absolute Arm RA-7312-4', '7312-5548-FA', 'in_stock', 'used', 750000, '{"year_built": 2018}'::jsonb, 'MTA (15)', 'ehem. Inv.-Nr. 21022', null),
  (153, 'Konstruktionsbüro', 'it', '6 27"-Monitore Dell/BenQ/Samsung', '6 27"-Monitore, Fabr. Dell/BenQ/Samsung',
   'Dell/BenQ/Samsung', null, null, 'in_stock', 'used', 18000, '{}'::jsonb, 'BGA (16)', null, null),
  (157, 'Büro Buchhaltung', 'it', '2 PC', '2 PC, älter, u.a. Fabr. XTPC, Intel Core i3, 2 27"-Monitore, Fabr. BenQ/Acer, 2 Tastaturen, 2 Mäuse',
   null, null, null, 'in_stock', 'used', 6000, '{}'::jsonb, 'BGA (16)', null, null),
  (158, 'Büro Buchhaltung', 'it', 'Multifunktionsdrucker HP LaserJet Pro 200 Color MFP', '1 Multifunktionsdrucker, Fabr. HP, Typ LaserJet Pro 200 Color MFP',
   'HP', 'LaserJet Pro 200 Color MFP', null, 'in_stock', 'used', 5000, '{}'::jsonb, 'BGA (16)', null, null),
  (159, 'Büro Buchhaltung', 'it', 'Aktenvernichter Schäfer Shop 420S', '1 Aktenvernichter, Fabr. Schäfer Shop, Typ 420S',
   'Schäfer Shop', '420S', null, 'in_stock', 'used', 5000, '{}'::jsonb, 'BGA (16)', null, null),
  (166, 'Fuhrpark', 'vehicle', 'Pkw Audi A4 2,0 TDI Avant', '1 Pkw, Fabr. Audi, Typ A4 2,0 TDI Avant, amtl. Kennz. LAU-ES 114, EZ 06/12, FIN WAUZZZ8K0DA060638, Diesel, Euro 5, 88 kW, 1.968 cm³, abgel. km-Stand 91.496, Außenfarbe dunkelblau, TÜV 06/25, allgemeine Gebrauchsspuren, schlechte Lackqualität, 8-fach bereift, Räder auf Alu-Leichtmetallfelgen, Innenausstattung Stoff, anthrazit, 6-Gang Schaltgetriebe, Navigationssystem (defekt), Klimaautomatik (defekt)',
   'Audi', 'A4 2,0 TDI Avant', 'WAUZZZ8K0DA060638', 'in_stock', 'used', 700000, '{"plate": "LAU-ES 114", "first_reg": "2012-06-01", "fuel": "Diesel", "power_kw": 88, "mileage_km": 91496, "inspection_until": "2025-06-30"}'::jsonb, 'KFZ (39)', null, '32002'),
  (167, 'Fuhrpark', 'vehicle', 'Pkw/Transporter Volkswagen Caddy 2,0 Ecofuel', '1 Pkw/Transporter, Fabr. Volkswagen, Typ Caddy 2,0 Ecofuel, amtl. Kennz. LAU-ES 60, EZ 04/13, FIN WV2ZZZ2KZDX113677, Benzin/Erdgas, Euro 5, 80 kW, 1.984 cm³, überm. km-Stand 129.679, Außenfarbe weiß, 5-Gang Schaltgetriebe, Klimaanlage, 2 Schiebetüren, Heckklappe, hinten m. Doppelsitz/Einzelsitz, entnehmbar, Mängel: schlechte Lackqualität, Rost, allgemeine Gebrauchsspuren, Anhängerkupplung, starr, PDC hinten',
   'Volkswagen', 'Caddy 2,0 Ecofuel', 'WV2ZZZ2KZDX113677', 'in_stock', 'used', 450000, '{"plate": "LAU-ES 60", "first_reg": "2013-04-01", "fuel": "Benzin/Erdgas", "power_kw": 80, "mileage_km": 129679, "trailer_hitch": true}'::jsonb, 'KFZ (39)', null, '32005'),
  (168, 'Fuhrpark', 'vehicle', 'Pkw Audi A3 Sportback 2,0 TDI', '1 Pkw, Fabr. Audi, Typ A3 Sportback 2,0 TDI, amtl. Kennz. LAU-ES 777, EZ 10/08, FIN WAUZZZ8P09AU43597, Diesel, Euro 4, 103 kW, 1.968 cm³, überm. km-Stand 219.632, 4-Türer, Außenfarbe blau, Innenausstattung Stoff, anthrazit, m. Klimaanlage, 6-Gang Schaltgetriebe, PDC vorne/hinten, allgemeine Gebrauchsspuren, schlechte Lackqualität, Lackkratzer, Steinschlagschäden, Scheinwerfer blind',
   'Audi', 'A3 Sportback 2,0 TDI', 'WAUZZZ8P09AU43597', 'in_stock', 'used', 190000, '{"plate": "LAU-ES 777", "first_reg": "2008-10-01", "fuel": "Diesel", "power_kw": 103, "mileage_km": 219632}'::jsonb, 'KFZ (39)', null, '32003'),
  (169, 'Fuhrpark', 'vehicle', 'Pkw-Anhänger TPV Prikolice C42', '1 Pkw-Anhänger, Fabr. TPV Prikolice, Typ C42, amtl. Kennz. LAU-ES 181, EZ 04/12, FIN ZY2EUAAAAA0068982, zul. GG 750 kg, Ladebordwände starr, m. Plane/Spriegel, 1-achsig',
   'TPV Prikolice', 'C42', 'ZY2EUAAAAA0068982', 'in_stock', 'used', 45000, '{"plate": "LAU-ES 181", "first_reg": "2012-04-01"}'::jsonb, 'KFZ (39)', null, null),
  (170, 'Fuhrpark', 'vehicle', 'Transporter Fiat Ducato 3,0 JTD 160 Multijet Kasten', '1 Transporter, Fabr. Fiat, Typ Ducato 3,0 JTD 160 Multijet Kasten, amtl. Kennz. LAU-ES 747, EZ 06/11, FIN ZFA25000001976988, Diesel, 116 kW, 2.999 cm³, überm. km-Stand 375.614, geschlossener Kasten, Hochdach, Radstand ca. 4.200 mm, Außenfarbe weiß, 6-Gang Schaltgetriebe, Anhängerkupplung, starr, Mängel: schlechter Allgemeinzustand, Lack stark verwittert, Hecktür verbogen, Beulen, Anfahrschaden rechts, Rostbefall',
   'Fiat', 'Ducato 3,0 JTD 160 Multijet Kasten', 'ZFA25000001976988', 'in_stock', 'used', 350000, '{"plate": "LAU-ES 747", "first_reg": "2011-06-01", "fuel": "Diesel", "power_kw": 116, "mileage_km": 375614, "trailer_hitch": true}'::jsonb, 'KFZ (39)', null, '38005')
)
insert into assets (company_id, category, name, manufacturer, model,
       serial_number, status, condition, location_id, purchase_date,
       purchase_price_cents, attributes, notes, created_by)
select '00b09d31-0231-4075-a44e-79a497419e72', r.kat, r.name, r.hersteller, r.modell, r.seriennr,
       r.status, r.zustand, l.id, date '2025-08-05', r.wert, r.attr,
       -- name ist gekürzt und steht auf dem Etikett, wortlaut ist der
       -- Text des Gutachters und eröffnet die Bemerkung.
       r.wortlaut || E'\n\n'
         || case when coalesce(r.bemerkung, '') = '' then ''
                 else 'Bemerkung des Gutachters: ' || r.bemerkung || E'\n' end
         || 'Übernommen aus dem Bewertungsgutachten der NetBid Auction & Valuation vom 05.08.2025 ("Bewertung Engelbreit & Sohn GmbH", Zuordnung nur Massebestandteil),'
         || ' Position ' || r.pos || ', Anlagengruppe ' || r.gruppe || E'.\n'
         || 'Der Anschaffungswert ist der Fortführungswert des Gutachtens, kein gezahlter Kaufpreis.'
         || case when coalesce(r.altnr, '') = '' then ''
                 else E'\n' || 'Alte Inventarnummer: ' || r.altnr || '.' end,
       '2877314a-1231-4767-ab24-0a6c4b466d47'
  from roh r
  left join locations l on l.company_id = '00b09d31-0231-4075-a44e-79a497419e72' and l.kind = 'room' and l.name = r.standort
 order by r.pos;

-- Gegenprobe: 103 Objekte, Summe 60.540,00 EUR wie auf Seite 12 des Gutachtens.
do $blk$
declare v_n int; v_s bigint;
begin
    select count(*), coalesce(sum(purchase_price_cents), 0) into v_n, v_s
      from assets where company_id = '00b09d31-0231-4075-a44e-79a497419e72';
    if v_n <> 103 or v_s <> 6054000 then
        raise exception 'Import weicht ab: % Objekte, % Cent', v_n, v_s;
    end if;
    raise notice 'Import in Ordnung: % Objekte, % Cent', v_n, v_s;
end $blk$;

commit;
