-- ===========================================================================
-- Trainingsplan „Zwölf Wochen zum Muscle-Up", Stand 19. September 2026.
--
-- ERZEUGT von scripts/generate-seed.mjs aus src/data/plan.ts — nicht von Hand
-- ändern. Änderungen am Plan gehören in plan.ts und danach in eine neue
-- Migration; der Seed ist idempotent und lässt sich erneut einspielen.
-- ===========================================================================

insert into exercises
  (id, name, equipment, unilateral, load_type, cue, primary_muscles, secondary_muscles)
values
  ('bankdruecken-lh', 'Bankdrücken Langhantel', 'langhantel', false, 'external',
   'Schulterblätter zusammen und nach unten, Ellbogen 45°, Stange zur unteren Brust.', '{chest}', '{triceps,front_delts}'),
  ('bankdruecken-kh', 'Bankdrücken Kurzhantel, flach', 'kurzhantel', false, 'external',
   'Hanteln tiefer als die Stange führen, unten kurz Spannung halten.', '{chest}', '{triceps,front_delts}'),
  ('schraegbankdruecken-kh', 'Schrägbankdrücken Kurzhantel', 'kurzhantel', false, 'external',
   'Bank auf 30°, oben nicht ganz durchstrecken.', '{chest}', '{triceps,front_delts}'),
  ('kabelzug-fly', 'Kabelzug-Fly, tiefe Endposition', 'kabel', false, 'external',
   'Züge von oben, Hände unterhalb der Brust kreuzen, gedehnte Endlage betonen.', '{chest}', '{}'),
  ('schulterdruecken-lh', 'Schulterdrücken Langhantel, stehend', 'langhantel', false, 'external',
   'Rippen unten lassen, Kopf durch, keine Ausweichbewegung im Rücken.', '{front_delts}', '{triceps}'),
  ('schulterdruecken-kh', 'Schulterdrücken Kurzhantel, sitzend', 'kurzhantel', false, 'external',
   'Lehne steil, Hanteln auf Schulterhöhe starten, Handflächen leicht zueinander.', '{front_delts}', '{triceps}'),
  ('dips-stange', 'Dips an der geraden Stange', 'stange', false, 'bodyweight_plus',
   'Oberkörper leicht vorgeneigt, Ellbogen dicht am Rumpf, tief genug herunter.', '{chest,triceps}', '{front_delts}'),
  ('trizeps-ueberkopf-kabel', 'Trizeps über Kopf am Kabel', 'kabel', false, 'external',
   'Ellbogen zeigen nach vorn, gedehnte Position bewusst ausfahren.', '{triceps}', '{}'),
  ('seitheben-kabel', 'Seitheben am Kabel, einarmig', 'kabel', true, 'external',
   'Zug hinter dem Rücken, Bewegung aus der Schulter, kein Schwung aus der Hüfte.', '{side_delts}', '{}'),
  ('klimmzuege-zusatzlast', 'Klimmzüge mit Zusatzlast', 'stange', false, 'bodyweight_plus',
   'Brustbein zur Stange, Ellbogen nach hinten unten, unten voll aushängen.', '{back_pull}', '{biceps}'),
  ('langhantelrudern', 'Langhantelrudern', 'langhantel', false, 'external',
   'Oberkörper 30–45°, Stange zum Bauchnabel, Rücken bleibt starr.', '{back_pull}', '{biceps}'),
  ('ringrudern', 'Ringrudern', 'ringe', false, 'bodyweight_plus',
   'Körper eine Linie, Ringe zum Rippenbogen, oben auswärts drehen.', '{back_pull}', '{biceps}'),
  ('latzug-eng', 'Latzug eng', 'kabel', false, 'external',
   'Enger Parallelgriff, Griff zur Brust, Oberkörper kaum bewegen.', '{back_pull}', '{biceps}'),
  ('face-pull', 'Face Pull', 'kabel', false, 'external',
   'Seil auf Augenhöhe, Hände an den Ohren vorbei, außenrotieren.', '{back_pull}', '{side_delts}'),
  ('hammercurl', 'Hammercurl', 'kurzhantel', false, 'external',
   'Neutralgriff, Oberarm still, unten vollständig strecken.', '{biceps}', '{}'),
  ('kniebeuge-hinten', 'Kniebeuge hinten, Langhantel', 'langhantel', false, 'external',
   'Stange auf dem hinteren Deltoid, Knie über die Zehen, unter Parallele.', '{quads}', '{hamstrings_glutes}'),
  ('rumaenisches-kreuzheben', 'Rumänisches Kreuzheben, Langhantel', 'langhantel', false, 'external',
   'Hüfte nach hinten, Stange am Bein, bis die Beinrückseite zieht.', '{hamstrings_glutes}', '{back_pull}'),
  ('kreuzheben', 'Kreuzheben konventionell, Langhantel', 'langhantel', false, 'external',
   'Stange über der Mitte des Fußes, Spannung vor dem Anzug, Hüfte und Schulter steigen gemeinsam.', '{hamstrings_glutes}', '{back_pull,quads}'),
  ('bulgarischer-split-squat', 'Bulgarischer Split Squat, Kurzhanteln', 'kurzhantel', true, 'external',
   'Hinterer Fuß erhöht, Rumpf leicht vorgeneigt, vorderes Knie über den Fuß.', '{quads}', '{hamstrings_glutes}'),
  ('gehende-ausfallschritte', 'Gehende Ausfallschritte, Kurzhanteln', 'kurzhantel', true, 'external',
   'Langer Schritt, Knie bis knapp über den Boden, aufrecht bleiben.', '{quads}', '{hamstrings_glutes}'),
  ('hip-thrust', 'Hip Thrust, Langhantel', 'langhantel', false, 'external',
   'Schulterblätter auf der Bank, Rippen unten, oben eine Sekunde halten.', '{hamstrings_glutes}', '{}'),
  ('nordic-curl', 'Nordic Curl', 'koerpergewicht', false, 'bodyweight',
   'Füße unter beladener Langhantel, Hüfte gestreckt, so lange bremsen wie möglich.', '{hamstrings_glutes}', '{}'),
  ('kettlebell-swing', 'Kettlebell Swing, russisch', 'kettlebell', false, 'external',
   'Hüftstoß, keine Kniebeuge, Kugel bis Brusthöhe, Arme bleiben locker.', '{hamstrings_glutes}', '{}'),
  ('wadenheben-stehend', 'Wadenheben stehend, Langhantel im Nacken', 'langhantel', false, 'external',
   'Ferse tief absenken, oben zwei Sekunden halten.', '{calves}', '{}'),
  ('wadenheben-einbeinig', 'Wadenheben einbeinig, Kurzhantel', 'kurzhantel', true, 'external',
   'Voller Bewegungsweg, freie Hand nur zum Ausbalancieren.', '{calves}', '{}'),
  ('ab-wheel', 'Ab Wheel', 'koerpergewicht', false, 'bodyweight',
   'Becken aufgerichtet, Rücken darf nicht durchhängen, nur so weit wie kontrolliert.', '{abs}', '{}'),
  ('hollow-hold', 'Hollow Hold', 'koerpergewicht', false, 'time',
   'Lendenwirbel am Boden, Beine tief, Schulterblätter frei.', '{abs}', '{}'),
  ('haengendes-beinheben', 'Hängendes Beinheben, gestreckt', 'stange', false, 'bodyweight',
   'Kein Schwung, Becken am Ende einrollen, langsam ablassen.', '{abs}', '{}'),
  ('kabel-crunch', 'Gewichteter Crunch am Kabel', 'kabel', false, 'external',
   'Kniend, Bewegung aus der Wirbelsäule, Hüfte bleibt ruhig.', '{abs}', '{}'),
  ('pallof-press', 'Pallof Press', 'kabel', true, 'external',
   'Gegen die Rotation halten, Arme langsam ausstrecken.', '{abs}', '{}'),
  ('koffertragen', 'Kettlebell-Koffertragen', 'kettlebell', true, 'distance',
   'Eine Kugel, Schultern waagerecht, nicht zur Gegenseite lehnen.', '{abs}', '{}')
on conflict (id) do update set
  name = excluded.name, equipment = excluded.equipment, unilateral = excluded.unilateral,
  load_type = excluded.load_type, cue = excluded.cue,
  primary_muscles = excluded.primary_muscles, secondary_muscles = excluded.secondary_muscles;

-- Pull steht zweimal im Zyklus, auf Position 2 und 6; die Tabelle hält nur eine
-- Position, die Rotation selbst liegt in src/lib/zyklus.ts.
insert into session_templates (id, name, headline, cycle_position, planned_minutes)
values
  ('push_a', 'Push A', 'Bankdrücken trägt den Tag', 1, 58),
  ('pull', 'Pull', 'Der Muscle-Up steht vorn, solange die Arme frisch sind', 2, 57),
  ('legs_a', 'Beine A', 'Kniebeuge trägt den Tag', 3, 57),
  ('push_b', 'Push B', 'Die Schulter kommt zuerst', 5, 58),
  ('legs_b', 'Beine B', 'Kreuzheben', 7, 55)
on conflict (id) do update set
  name = excluded.name, headline = excluded.headline,
  cycle_position = excluded.cycle_position, planned_minutes = excluded.planned_minutes;

-- Feste Kennungen: sets.block_id verweist darauf, und die App kennt die Vorlage
-- auch offline. 1xx Push A, 2xx Push B, 3xx Pull, 4xx Beine A, 5xx Beine B.
insert into template_blocks
  (id, template_id, ordinal, label, superset_group, exercise_id, kind,
   target_sets, rep_min, rep_max, target_rir, rest_seconds, planned_minutes, note)
values
  (101, 'push_a', 1, '1', null,
   null, 'warmup', null, null, null,
   null, null, 6, 'Rudergerät 2 Min, Bandzüge für die Rotatoren, 3 Steigerungssätze Bank.'),
  (102, 'push_a', 2, '2', null,
   'bankdruecken-lh', 'work', 5, 5, 7,
   '2', 165, 15, null),
  (103, 'push_a', 3, '3', null,
   'schulterdruecken-kh', 'work', 3, 8, 10,
   '2', 120, 7, null),
  (104, 'push_a', 4, '4', null,
   'dips-stange', 'work', 3, 6, 10,
   '1', 120, 7, 'Muscle-Up-Baustein — der tiefe Endpunkt ist der Punkt, nicht die Wiederholungszahl.'),
  (105, 'push_a', 5, '5a', 'pa5',
   'schraegbankdruecken-kh', 'work', 3, 8, 12,
   '1', 60, 9, null),
  (106, 'push_a', 6, '5b', 'pa5',
   'trizeps-ueberkopf-kabel', 'work', 3, 10, 12,
   '0-1', 60, 0, null),
  (107, 'push_a', 7, '6', null,
   'seitheben-kabel', 'work', 4, 12, 20,
   '0-1', 45, 6, null),
  (108, 'push_a', 8, '7a', 'pa7',
   'ab-wheel', 'abs', 4, 8, 12,
   '1', 45, 8, null),
  (109, 'push_a', 9, '7b', 'pa7',
   'hollow-hold', 'abs', 4, 20, 30,
   '1', 45, 0, null),
  (201, 'push_b', 1, '1', null,
   null, 'warmup', null, null, null,
   null, null, 6, 'Schulterkreisen, Bandzüge, 3 Steigerungssätze Schulterdrücken.'),
  (202, 'push_b', 2, '2', null,
   'schulterdruecken-lh', 'work', 5, 5, 8,
   '2', 165, 15, null),
  (203, 'push_b', 3, '3', null,
   'bankdruecken-kh', 'work', 3, 8, 12,
   '1', 120, 7, null),
  (204, 'push_b', 4, '4', null,
   'dips-stange', 'work', 3, 5, 8,
   '1', 120, 7, 'Mit Zusatzlast — Gürtel oder Hantel zwischen den Füßen.'),
  (205, 'push_b', 5, '5a', 'pb5',
   'kabelzug-fly', 'work', 3, 12, 15,
   '0-1', 60, 9, null),
  (206, 'push_b', 6, '5b', 'pb5',
   'trizeps-ueberkopf-kabel', 'work', 3, 10, 12,
   '0-1', 60, 0, null),
  (207, 'push_b', 7, '6', null,
   'seitheben-kabel', 'work', 4, 12, 20,
   '0-1', 45, 6, null),
  (208, 'push_b', 8, '7a', 'pb7',
   'ab-wheel', 'abs', 4, 8, 12,
   '1', 45, 8, null),
  (209, 'push_b', 9, '7b', 'pb7',
   'hollow-hold', 'abs', 4, 20, 30,
   '1', 45, 0, null),
  (301, 'pull', 1, '1', null,
   null, 'warmup', null, null, null,
   null, null, 6, 'Hängen 30 s, Bandzüge, Schulterblatt-Klimmzüge 2 × 8.'),
  (302, 'pull', 2, '2', null,
   null, 'muscleup', null, null, null,
   '2-3', 90, 12, 'Inhalt nach Phase — die Übungen stehen auf dem Muscle-Up-Schirm.'),
  (303, 'pull', 3, '3', null,
   'klimmzuege-zusatzlast', 'work', 4, 4, 6,
   '1', 150, 11, 'Brustbein zur Stange.'),
  (304, 'pull', 4, '4', null,
   'langhantelrudern', 'work', 4, 6, 8,
   '2', 120, 9, null),
  (305, 'pull', 5, '5a', 'pl5',
   'ringrudern', 'work', 3, 10, 12,
   '1', 45, 11, 'Alternative bei besetzten Ringen: Latzug eng, gleiche Vorgabe.'),
  (306, 'pull', 6, '5b', 'pl5',
   'face-pull', 'work', 3, 15, 20,
   '0-1', 45, 0, null),
  (307, 'pull', 7, '5c', 'pl5',
   'hammercurl', 'work', 3, 8, 12,
   '0-1', 45, 0, null),
  (308, 'pull', 8, '6', null,
   'haengendes-beinheben', 'abs', 4, 8, 12,
   '1', 45, 8, null),
  (401, 'legs_a', 1, '1', null,
   null, 'warmup', null, null, null,
   null, null, 6, 'Seilspringen 2 Min, Hüftmobilisation, 3 Steigerungssätze Kniebeuge.'),
  (402, 'legs_a', 2, '2', null,
   'kniebeuge-hinten', 'work', 5, 5, 7,
   '2', 165, 15, null),
  (403, 'legs_a', 3, '3', null,
   'rumaenisches-kreuzheben', 'work', 4, 8, 10,
   '2', 120, 9, null),
  (404, 'legs_a', 4, '4', null,
   'bulgarischer-split-squat', 'work', 3, 10, 12,
   '1', 90, 10, null),
  (405, 'legs_a', 5, '5a', 'la5',
   'nordic-curl', 'work', 3, 5, 8,
   '1', 60, 9, 'Füße unter beladener Langhantel.'),
  (406, 'legs_a', 6, '5b', 'la5',
   'wadenheben-stehend', 'work', 3, 10, 15,
   '0-1', 60, 0, null),
  (407, 'legs_a', 7, '6a', 'la6',
   'pallof-press', 'abs', 3, 10, 10,
   '1', 45, 8, null),
  (408, 'legs_a', 8, '6b', 'la6',
   'koffertragen', 'abs', 3, 30, 30,
   '1', 45, 0, '30 m je Satz, Seite wechseln.'),
  (501, 'legs_b', 1, '1', null,
   null, 'warmup', null, null, null,
   null, null, 7, 'Seilspringen 3 Min, Katze-Kuh, Hüftöffner, 3 Steigerungssätze Kreuzheben.'),
  (502, 'legs_b', 2, '2', null,
   'kreuzheben', 'work', 5, 3, 5,
   '2', 180, 16, null),
  (503, 'legs_b', 3, '3', null,
   'hip-thrust', 'work', 3, 8, 12,
   '1', 90, 7, null),
  (504, 'legs_b', 4, '4', null,
   'gehende-ausfallschritte', 'work', 3, 10, 10,
   '1', 90, 8, 'Zehn Schritte je Bein, ohne Zwischenstopp.'),
  (505, 'legs_b', 5, '5a', 'lb5',
   'kettlebell-swing', 'work', 3, 12, 15,
   '1', 60, 9, null),
  (506, 'legs_b', 6, '5b', 'lb5',
   'wadenheben-einbeinig', 'work', 3, 12, 15,
   '0-1', 60, 0, null),
  (507, 'legs_b', 7, '6', null,
   'kabel-crunch', 'abs', 4, 10, 12,
   '0-1', 45, 8, null)
on conflict (id) do update set
  template_id = excluded.template_id, ordinal = excluded.ordinal, label = excluded.label,
  superset_group = excluded.superset_group, exercise_id = excluded.exercise_id,
  kind = excluded.kind, target_sets = excluded.target_sets, rep_min = excluded.rep_min,
  rep_max = excluded.rep_max, target_rir = excluded.target_rir,
  rest_seconds = excluded.rest_seconds, planned_minutes = excluded.planned_minutes,
  note = excluded.note;

insert into muscleup_blocks (id, name, week_from, week_to, gate)
values
  (1, 'Zugkraft und Falschgriff', 1, 4, '5 Klimmzüge mit +10 kg, und die explosiven Wiederholungen treffen das Brustbein.'),
  (2, 'Der Übergang', 5, 8, '3 kontrollierte Negative ohne Einbruch im Übergang.'),
  (3, 'Die ganze Bewegung', 9, 12, 'Erster Ring-Muscle-Up, danach Übertrag auf die Stange.')
on conflict (id) do update set
  name = excluded.name, week_from = excluded.week_from,
  week_to = excluded.week_to, gate = excluded.gate;

insert into muscleup_drills (id, block_id, ordinal, name, prescription, cue)
values
  (1, 1, 1, 'Explosive Klimmzüge', '6 × 3', 'Satz endet, sobald die Geschwindigkeit nachlässt — auch nach zwei Wiederholungen.'),
  (2, 1, 2, 'Falschgriff-Hang an den Ringen', '4 × 20–30 s', 'Handgelenk über den Ring, Ring in der Handwurzel. Brennt, gehört dazu.'),
  (3, 2, 1, 'Negative Ring-Muscle-Ups vom Kasten', '5 × 3', 'Abstieg 4–5 s, im Übergang nicht durchrutschen.'),
  (4, 2, 2, 'Übergangswiederholungen mit Fußkontakt', '4 × 5', 'Füße geben nur so viel, wie der Übergang braucht.'),
  (5, 2, 3, 'Explosive Klimmzüge', '3 × 3', 'Kurz halten, Qualität vor Zahl.'),
  (6, 3, 1, 'Versuche', '6 × 1', '2–3 Minuten Pause. Jeder Versuch frisch.'),
  (7, 3, 2, 'Bandunterstützt an den Ringen', '3 × 3', 'Band so dünn wie möglich.'),
  (8, 3, 3, 'Hohe Klimmzüge zur unteren Rippe', '3 × 3', 'So hoch wie es geht, ohne den Griff zu lösen.')
on conflict (id) do update set
  block_id = excluded.block_id, ordinal = excluded.ordinal, name = excluded.name,
  prescription = excluded.prescription, cue = excluded.cue;

